name: SonarCloud Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # or your project's Node version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test   # Optional; include only if you have tests

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.10
        with:
          organization: ashishproponenttech
          projectKey: ashishproponenttech_sonu-hair-app
          token: ${{ secrets.SONAR_TOKEN }}
